/**
 * The start-screen banner shared by every agent: the wordmark, the greeting
 * and the palette. Pure data and functions only, since each agent runs it in
 * a different runtime (Pi's jiti, OpenCode's Bun, Claude Code's hook sandbox
 * with no Node) and draws it with its own UI API.
 *
 * `identity.ts` beside this file is generated by `default.nix` from
 * `home.username`.
 */
import { identity } from "./identity";

/** Catppuccin Mocha, the palette every terminal and editor here uses. */
export const mocha = {
  rosewater: "#f5e0dc",
  flamingo: "#f2cdcd",
  pink: "#f5c2e7",
  mauve: "#cba6f7",
  red: "#f38ba8",
  maroon: "#eba0ac",
  peach: "#fab387",
  yellow: "#f9e2af",
  green: "#a6e3a1",
  teal: "#94e2d5",
  sky: "#89dceb",
  sapphire: "#74c7ec",
  blue: "#89b4fa",
  lavender: "#b4befe",
  text: "#cdd6f4",
  subtext0: "#a6adc8",
  overlay1: "#7f849c",
} as const;

export type Agent = "claude" | "pi" | "opencode";

/**
 * Every agent draws the same wordmark, tinted left to right with its own
 * gradient so it is obvious at a glance which one is open.
 */
export const gradients: Record<Agent, readonly string[]> = {
  claude: [mocha.peach, mocha.maroon, mocha.mauve],
  pi: [mocha.sapphire, mocha.blue, mocha.lavender],
  opencode: [mocha.green, mocha.teal, mocha.sky],
};

export const name = identity.name;

/** Three rows of block glyphs spelling `name` (toilet's pagga font). */
export const wordmark: readonly string[] = identity.wordmark;

export const wordmarkWidth = Math.max(...wordmark.map((line) => [...line].length));

export type Run = { text: string; color?: string };

/**
 * Splits one wordmark row into runs of a single color, sampling the gradient
 * by column so every row lines up. Spaces get no color.
 */
export function shade(line: string, stops: readonly string[]): Run[] {
  const runs: Run[] = [];
  [...line].forEach((glyph, column) => {
    const color = glyph === " " ? undefined : mix(stops, column / Math.max(1, wordmarkWidth - 1));
    const last = runs[runs.length - 1];
    if (last && last.color === color) last.text += glyph;
    else runs.push({ text: glyph, color });
  });
  return runs;
}

/** Linear sRGB interpolation across evenly spaced `#rrggbb` stops, `t` in [0, 1]. */
export function mix(stops: readonly string[], t: number): string {
  const position = Math.min(1, Math.max(0, t)) * (stops.length - 1);
  const index = Math.max(0, Math.min(stops.length - 2, Math.floor(position)));
  const from = rgb(stops[index]);
  const to = rgb(stops[index + 1] ?? stops[index]);
  const local = position - index;
  const channels = from.map((start, i) => Math.round(start + ((to[i] ?? start) - start) * local));
  return `#${channels.map((channel) => channel.toString(16).padStart(2, "0")).join("")}`;
}

function rgb(hex = "#000000"): number[] {
  return [1, 3, 5].map((offset) => parseInt(hex.slice(offset, offset + 2), 16));
}

export function greeting(hour: number): string {
  if (hour < 5) return `Up late, ${name}`;
  if (hour < 12) return `Good morning, ${name}`;
  if (hour < 18) return `Good afternoon, ${name}`;
  return `Good evening, ${name}`;
}

const weekdays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/** `Thursday 8 October · 1:20 PM`, the 12-hour clock the status line uses. */
export function dateline(now: Date): string {
  const hour12 = now.getHours() % 12 || 12;
  const minutes = String(now.getMinutes()).padStart(2, "0");
  const meridiem = now.getHours() < 12 ? "AM" : "PM";
  return `${weekdays[now.getDay()]} ${now.getDate()} ${months[now.getMonth()]} · ${hour12}:${minutes} ${meridiem}`;
}

/** The last path segment, or `~` for the home directory. */
export function project(cwd: string, home?: string): string {
  if (home && cwd.replace(/\/+$/, "") === home.replace(/\/+$/, "")) return "~";
  return cwd.split("/").filter(Boolean).pop() ?? "/";
}

/**
 * `label on <host>`, where it runs. The host is left out when it is named
 * after the user, as the desktop is, so the line doesn't repeat the greeting.
 */
export function signature(label: string, host: string): string {
  return !host || host === name ? label : `${label} on ${host}`;
}
